// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btcgeqbuybssufdbykdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Y2dlcWJ1eWJzc3VmZGJ5a2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjczMzIsImV4cCI6MjA2MjMwMzMzMn0.1NgADgjJ1jTTfucDPu0tVc7H-CI2rit6lx9glu6TTmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);